### ISSUE TITLE
脚本失效

### ISSUE THREAD

**Issue by litesheng** [Marol62926/Loon#1]
百色特和proknockout失效，当然也是因为版本更新了，不知道作者能不能适配最新版本，不会抓去旧版软件，如果不方便就算了，抱歉打扰了。

**Comment by Marol62926** [comment]
> 百色特和proknockout失效，当然也是因为版本更新了，不知道作者能不能适配最新版本，不会抓去旧版软件，如果不方便就算了，抱歉打扰了。

https://buy.itunes.apple.com/verifyReceipt 这个重写url的问题，使用的时候把有相同的hostname的脚本注释掉，只开启相应app的重写就行了；这个有一个脚本匹配的问题，优先匹配本地脚本，远程脚本优先级低一点，可能是这个原因，把其他带有buy.itunes.apple.com的脚本注释或禁用就行了。

**Comment by Marol62926** [comment]
https://buy.itunes.apple.com/verifyReceipt&nbsp;这个重写url的问题，使用的时候把有相同的hostname的脚本注释掉，只开启相应app的重写就行了；这个有一个脚本匹配的问题，优先匹配本地脚本，远程脚本优先级低一点，可能是这个原因，把其他带有buy.itunes.apple.com的脚本注释或禁用就行了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Marol62926/Loon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月7日(星期五) 上午10:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Marol62926/Loon] 脚本失效 (Issue #1)





 
百色特和proknockout失效，当然也是因为版本更新了，不知道作者能不能适配最新版本，不会抓去旧版软件，如果不方便就算了，抱歉打扰了。

**Comment by litesheng** [comment]
刚才又试了 确实不行 应该还是版本问题 不麻烦了 谢谢 这个提交可以关闭了 谢谢

**Comment by Marol62926** [comment]
> 

我之前重新测了一下，我用Quantumultx是可以正常解锁的，可能有一些其他问题吧，抓包的话你用旧版itunes和一个小工具就行了，百度就有的，很简单的。

**Comment by Marol62926** [comment]
> 刚才又试了 确实不行 应该还是版本问题 不麻烦了 谢谢 这个提交可以关闭了 谢谢
> […](#)
> 在 2022年10月7日，11:37，Marol62926 ***@***.***> 写道： ﻿ [https://buy.itunes.apple.com/verifyReceipt&nbsp;这个重写url的问题，使用的时候把有相同的hostname的脚本注释掉，只开启相应app的重写就行了；这个有一个脚本匹配的问题，优先匹配本地脚本，远程脚本优先级低一点，可能是这个原因，把其他带有buy.itunes.apple.com的脚本注释或禁用就行了。](https://buy.itunes.apple.com/verifyReceipt&nbsp;%E8%BF%99%E4%B8%AA%E9%87%8D%E5%86%99url%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%BD%BF%E7%94%A8%E7%9A%84%E6%97%B6%E5%80%99%E6%8A%8A%E6%9C%89%E7%9B%B8%E5%90%8C%E7%9A%84hostname%E7%9A%84%E8%84%9A%E6%9C%AC%E6%B3%A8%E9%87%8A%E6%8E%89%EF%BC%8C%E5%8F%AA%E5%BC%80%E5%90%AF%E7%9B%B8%E5%BA%94app%E7%9A%84%E9%87%8D%E5%86%99%E5%B0%B1%E8%A1%8C%E4%BA%86%EF%BC%9B%E8%BF%99%E4%B8%AA%E6%9C%89%E4%B8%80%E4%B8%AA%E8%84%9A%E6%9C%AC%E5%8C%B9%E9%85%8D%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%BC%98%E5%85%88%E5%8C%B9%E9%85%8D%E6%9C%AC%E5%9C%B0%E8%84%9A%E6%9C%AC%EF%BC%8C%E8%BF%9C%E7%A8%8B%E8%84%9A%E6%9C%AC%E4%BC%98%E5%85%88%E7%BA%A7%E4%BD%8E%E4%B8%80%E7%82%B9%EF%BC%8C%E5%8F%AF%E8%83%BD%E6%98%AF%E8%BF%99%E4%B8%AA%E5%8E%9F%E5%9B%A0%EF%BC%8C%E6%8A%8A%E5%85%B6%E4%BB%96%E5%B8%A6%E6%9C%89buy.itunes.apple.com%E7%9A%84%E8%84%9A%E6%9C%AC%E6%B3%A8%E9%87%8A%E6%88%96%E7%A6%81%E7%94%A8%E5%B0%B1%E8%A1%8C%E4%BA%86%E3%80%82) ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Marol62926/Loon" ***@***.***&gt;; 发送时间:&nbsp;2022年10月7日(星期五) 上午10:30 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Marol62926/Loon] 脚本失效 (Issue #1) 百色特和proknockout失效，当然也是因为版本更新了，不知道作者能不能适配最新版本，不会抓去旧版软件，如果不方便就算了，抱歉打扰了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

我之前重新测了一下，我用Quantumultx是可以正常解锁的，可能有一些其他问题吧，抓包的话你用旧版itunes和一个小工具就行了，百度就有的，很简单的。

**Comment by litesheng** [comment]
嗯好的 可能还是新版的问题
